let
    ソース = _振替伝票_ソース,
    ピボット解除 = Table.Unpivot(
        ソース,
        {"仕入", "仕入割引", "協賛金", "販売促進費", "雑収入", "荷造運賃", "売掛金", "その他"},
        "勘定科目",
        "金額"
    ),
    行選択 = Table.SelectRows(ピボット解除, each [金額] <> 0),
    マスタ = [
        仕入 =[勘定科目 = "仕入", 補助科目 = "課税仕入", 税区分 = "課税対応仕入10%"],
        仕入割引 =[勘定科目 = "仕入割引", 補助科目 = "相殺", 税区分 = "課税対応仕入返還10%"],
        協賛金 =[勘定科目 = "協賛金", 補助科目 = null, 税区分 = "課税売上10%"],
        販売促進費 =[勘定科目 = "販売促進費", 補助科目 = "その他", 税区分 = "課税対応仕入10%"],
        雑収入 =[勘定科目 = "雑収入", 補助科目 = "相殺", 税区分 = "課税売上10%"],
        荷造運賃 =[勘定科目 = "荷造運賃", 補助科目 = "課税", 税区分 = "課税対応仕入10%"],
        売掛金 =[勘定科目 = "売掛金", 補助科目 = "取引先", 税区分 = "対象外"],
        その他 =[勘定科目 = null, 補助科目 = null, 税区分 = null]
    ],
    
    // --- 追加：インデックス列の付与と全体の行数を取得 ---
    インデックス付き = Table.AddIndexColumn(行選択, "Index", 0, 1, Int64.Type),
    行数 = Table.RowCount(インデックス付き),

    行変換 = Table.TransformRows(
        インデックス付き,
        each
            let
                対象マスタ = Record.FieldOrDefault(
                    マスタ,
                    [勘定科目],
                    [勘定科目 = null, 補助科目 = null, 税区分 = null]
                ),
                買掛金 = [勘定科目 = "買掛金", 補助科目 = [補助科目名], 税区分 = "対象外"],
                借方 = if [金額] > 0 then 対象マスタ else 買掛金,
                貸方 = if [金額] > 0 then 買掛金 else 対象マスタ,
                金額 = Number.Abs([金額]),
                
                // --- 追加：伝票分割と採番のロジック ---
                // 20行ごとに伝票番号をインクリメント（1始まり）
                伝票番号値 = Number.IntegerDivide([Index], 20) + 1,
                
                // グループ(20行)内での行番号（0～19）
                グループ内Index = Number.Mod([Index], 20),
                
                // フラグ判定用のフラグ
                isFirst = (グループ内Index = 0),
                isLast = (グループ内Index = 19 or[Index] = 行数 - 1),
                
                // 弥生会計の仕様に沿った識別フラグの判定
                識別フラグ値 = if isFirst and isLast then 2111
                             else if isFirst then 2110
                             else if isLast then 2101
                             else 2100
            in[
                    識別フラグ = 識別フラグ値,
                    伝票番号 = 伝票番号値,
                    決算 = null,
                    取引日付 = _基準日,
                    借方勘定科目 = 借方[勘定科目],
                    借方補助科目 = 借方[補助科目],
                    借方部門 = null,
                    借方税区分 = 借方[税区分],
                    借方金額 = 金額,
                    借方税金額 = null,
                    貸方勘定科目 = 貸方[勘定科目],
                    貸方補助科目 = 貸方[補助科目],
                    貸方部門 = null,
                    貸方税区分 = 貸方[税区分],
                    貸方金額 = 金額,
                    貸方税金額 = null,
                    摘要 = [仕入先名],
                    番号 = null,
                    期日 = null,
                    タイプ = 3,
                    生成元 = null,
                    仕訳メモ = null,
                    付箋1 = null,
                    付箋2 = null,
                    調整 = null
                ]
    ),
    テーブル化 = Table.FromRecords(
        行変換,
        {
            "識別フラグ",
            "伝票番号",
            "決算",
            "取引日付",
            "借方勘定科目",
            "借方補助科目",
            "借方部門",
            "借方税区分",
            "借方金額",
            "借方税金額",
            "貸方勘定科目",
            "貸方補助科目",
            "貸方部門",
            "貸方税区分",
            "貸方金額",
            "貸方税金額",
            "摘要",
            "番号",
            "期日",
            "タイプ",
            "生成元",
            "仕訳メモ",
            "付箋1",
            "付箋2",
            "調整"
        }
    )
in
    テーブル化
